name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 18.206.69.251
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd ~/flask_project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flaskapp
            sudo systemctl restart nginx
